### ISSUE TITLE
uncaughtException TypeError: Cannot read property 'ts' of undefined

### ISSUE THREAD

**Issue by atomantic** [yahoo/dnscache#19]
```
uncaughtException TypeError: Cannot read property 'ts' of undefined
    at /app/node_modules/dnscache/lib/cache.js:87:63
```
apparently `self.data[key]` does not exist:
```
if (conf.ttl !== 0 && (Date.now() - self.data[key].ts) >= self.ttl) {
```

**Comment by andris9** [comment]
I have had the same issue. It seems that while `next()` (from the `asap` module) executes, then `self.data[key]` gets expired

**Comment by Michel73** [comment]
I run into the same issue. I think the reason is that in line 110 of cache.js `delete self.data[key];`.

**Comment by Neamar** [comment]
Same here when upgrading from 0.0.4 to 1.0.0

**Comment by drewfish** [comment]
Thanks!

**Comment by drewfish** [comment]
Published dnscache@1.0.1 to npm, let me know if it fixes this issue.

**Comment by tikotzky** [comment]
fixed it for me 😉 
Thanks.

**Comment by drewfish** [comment]
OK, looks like it's fixed. Feel free to re-open if you see this again.
